spring:
  application:
    name: form-flow
  
  datasource:
    url: jdbc:postgresql://localhost:5432/formflow
    username: formflow
    password: formflow123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  security:
    user:
      name: admin
      password: admin123

server:
  port: 8080
  servlet:
    context-path: /
  shutdown: graceful

# Swagger/OpenAPI 配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: false

# 日誌配置
logging:
  level:
    com.formflow: INFO
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n"

# 管理端點配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

# 應用信息
info:
  app:
    name: FormFlow
    description: 表單工作流系統
    version: 1.0.0
    encoding: UTF-8
    java:
      version: 17